[package]

name = "disjoint-set"
version = "0.0.1"
authors = ["jaeju kim <jjkim@arcs.skku.edu>"]
license = "MIT"

description = "A implementation of Tarjan's Union-Find Data Structure."
repository = "https://github.com/azurespace/union-find"

